# Generated by Django 4.2.7 on 2023-11-18 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_carmodification_city_cargeneration_car_type_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodification',
            name='engine_volume',
            field=models.IntegerField(max_length=20, verbose_name='Обьем двигателя'),
        ),
    ]
