# Generated by Django 4.2.7 on 2023-11-18 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_post_options_post_is_new_post_not_move_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImageFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_files', to='cars.file')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='cars.post')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
